handlingValues = {
	{"Velocidade máxima (Km/h)", 0.1, 275, ref = 'maxVelocity'},
	{"Aceleração", 0.1, 75, ref = 'engineAcceleration'},
	{"Inércia do motor", 0.1, 30, ref = 'engineInertia'},
	
	{"Altura de suspensão", -0.375, 0.1, ref = 'suspensionLowerLimit'},
	{"Viés da Suspensão", 0.05, 0.95, ref = 'suspensionFrontRearBias'},
	{"Força de Suspensão", 0.01, 3, ref = 'suspensionForceLevel'},
	{"Amortecimento da suspensão", 0.01, 0.2, ref = 'suspensionDamping'},
	{"Bloqueio de direção", 0.1, 55, ref = 'steeringLock'},
	
	{"Peso maciço (Kg)", 50, 10000, ref = 'mass'},
	{"Centro de massa X", -1, 1, ref = 'centerOfMassX'},
	{"Centro de massa Y", -1, 1, ref = 'centerOfMassY'},
	{"Centro de massa Z", -1, 1, ref = 'centerOfMassZ'},

	{"Coeficiente de arrasto", 0.1, 6, ref = 'dragCoeff'},
	{"Potência de travagem", 0.1, 50, ref = 'brakeDeceleration'},
	{"Viés de frenagem", 0.1, 1, ref = 'brakeBias'},
	{"Multiplicador de Tracção", 0.1, 6, ref = 'tractionMultiplier'},
	{"Tendência de Tração", 0.1, 1, ref = 'tractionBias'},
}

handlings = {
	[1]={"mass", mass},
	[2]={"turnMass", turnMass},
	[3]={"dragCoeff", dragCoeff},
	[4]={"centerOfMass", centerOfMass, true},
	[5]={"percentSubmerged", percentSubmerged},
	[6]={"tractionMultiplier", tractionMultiplier},
	[7]={"tractionLoss", tractionLoss},
	[8]={"tractionBias", tractionBias},
	[9]={"numberOfGears", numberOfGears},
	[10]={"maxVelocity", maxVelocity},
	[11]={"engineAcceleration", engineAcceleration},
	[12]={"engineInertia", engineInertia},
	[13]={"driveType", driveType, false, true},
	[14]={"engineType", engineType, false, true},
	[14]={"engineType", engineType, false, true},
	[15]={"brakeDeceleration", brakeDeceleration},
	[16]={"brakeBias", brakeBias},
	[17]={"ABS", ABS},
	[18]={"steeringLock", steeringLock},
	[19]={"suspensionForceLevel", suspensionForceLevel},
	[20]={"suspensionDamping", suspensionDamping},
	[21]={"suspensionHighSpeedDamping", suspensionHighSpeedDamping},
	[22]={"suspensionUpperLimit", suspensionUpperLimit},
	[23]={"suspensionLowerLimit", suspensionLowerLimit},
	[24]={"suspensionFrontRearBias", suspensionFrontRearBias},
	[25]={"suspensionAntiDiveMultiplier", suspensionAntiDiveMultiplier},
	[26]={"seatOffsetDistance", seatOffsetDistance},
	[27]={"collisionDamageMultiplier", collisionDamageMultiplier},
	[28]={"monetary", monetary},
	[29]={"modelFlags", modelFlags},
	[30]={"handlingFlags", handlingFlags},
	[31]={"headLight", headLight, false, true},
	[32]={"tailLight", tailLight, false, true},
	[33]={"animGroup", animGroup}
}